"""
Template rendering and filesystem mutation for PROJECT module.
"""

from pathlib import Path
from datetime import datetime, timezone

from config.project_config import REQUIRED_PROJECT_DIRS, REQUIRED_PROJECT_FILES
from models.enums import ScaffoldAction, TargetClassification
from models.project_result import ScaffoldResult


def _generate_project_yaml(slug: str) -> str:
    """Generates the content for project.yaml."""
    now = datetime.now(timezone.utc).isoformat()
    return f"""# Framework Project Metadata
# DO NOT EDIT THIS FILE MANUALLY UNLESS INSTRUCTED.
# This file is used for identity verification by DEPLOY and OPERATE.

project_slug: {slug}
template_id: standard-vps
template_version: "1.0"
scaffold_created_at: "{now}"
"""


def _generate_compose_yaml(slug: str) -> str:
    """Generates a minimal baseline compose.yaml."""
    return f"""# Baseline Deployment Stack for {slug}
# Generated by VPS Framework

services:
  app:
    image: alpine:latest
    command: ["sleep", "infinity"]
    restart: always
    environment:
      - PROJECT_ID={slug}
"""


def _generate_env_example() -> str:
    return """# Environment variables template
PROJECT_ENV=production
"""


def _generate_gitignore() -> str:
    return """# Framework ignores
.env
__pycache__/
*.pyc
"""


def _generate_readme(slug: str) -> str:
    return f"""# {slug}

Generated by VPS Framework `new-project`.

## Structure
- `app/`: Application source code
- `config/`: Application configuration
- `deploy/`: Deployment scripts and assets
- `docs/`: Project documentation
- `operate/`: Operational scripts (backups, etc)
- `tests/`: Project tests
"""


def materialize_scaffold(
    target_path: Path, slug: str, classification: TargetClassification
) -> ScaffoldResult:
    """
    Creates the project scaffold at the target path.
    Only proceeds if classification is CLEAN, COMPATIBLE, or SANEABLE.
    If COMPATIBLE, preserves existing core files.
    """
    if classification == TargetClassification.BLOCKED:
        return ScaffoldResult(
            classification=classification,
            actions_taken=[ScaffoldAction.BLOCK],
            blocked_reason="Cannot materialize into a BLOCKED target path.",
        )

    actions_taken = []
    created_paths = []
    reused_paths = []

    # 1. Create root directory if needed
    if not target_path.exists():
        target_path.mkdir(parents=True)
        created_paths.append(target_path)
        actions_taken.append(ScaffoldAction.CREATE)
    else:
        reused_paths.append(target_path)
        actions_taken.append(ScaffoldAction.REUSE)

    # 2. Create directories
    for d in REQUIRED_PROJECT_DIRS:
        dir_path = target_path / d
        if not dir_path.exists():
            dir_path.mkdir()
            created_paths.append(dir_path)
            if ScaffoldAction.CREATE not in actions_taken:
                actions_taken.append(ScaffoldAction.CREATE)
        else:
            reused_paths.append(dir_path)

    # 3. Create/Reuse Files
    files_to_generate = {
        "project.yaml": _generate_project_yaml(slug),
        "compose.yaml": _generate_compose_yaml(slug),
        ".env.example": _generate_env_example(),
        ".gitignore": _generate_gitignore(),
        "README.md": _generate_readme(slug),
    }

    for filename, content in files_to_generate.items():
        file_path = target_path / filename
        if not file_path.exists():
            file_path.write_text(content, encoding="utf-8")
            created_paths.append(file_path)
        else:
            reused_paths.append(file_path)

    return ScaffoldResult(
        classification=classification,
        actions_taken=actions_taken,
        created_paths=created_paths,
        reused_paths=reused_paths,
        validation_passed=True,  # Assuming success if no exceptions
    )
